# Generated by Django 5.2.6 on 2025-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='altura_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
