# Generated by Django 5.2.6 on 2025-10-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_altura_m_perfil_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('GANHO', 'Ganhar massa magra'), ('PERDA', 'Perder peso'), ('MANUT', 'Manter peso')], default='', max_length=6),
        ),
    ]
