"""
Generated by Django on 2025-11-07
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_altura_m_perfil_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='notificacao_horario',
            field=models.TimeField(blank=True, null=True, help_text='Horário diário para notificações'),
        ),
    ]
