# Generated by Django 5.2.6 on 2025-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='calorias_gastas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='meta_calorias',
            field=models.IntegerField(blank=True, help_text='Meta de calorias a perder', null=True),
        ),
    ]
