# Generated by Django 5.2.6 on 2025-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_atividade_calorias_gastas_perfil_meta_calorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='meta_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
