# Generated by Django 5.2.6 on 2025-11-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_add_notificacao_horario'),
        ('perfil', '0005_perfil_meta_set_at'),
    ]

    operations = [
    ]
