# Generated by Django 5.2.6 on 2025-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medalhas', '0002_create_initial_medals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermedal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
