# Generated by Django 5.2.6 on 2025-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='gasto_kcal_por_hora',
            field=models.FloatField(blank=True, help_text='Gasto calórico médio por hora', null=True),
        ),
    ]
